config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'adminds/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/widthdraw' => 'customers#widthdraw', as: "customers_widthdraw"
    resources :customers, only:[:edit, :update]

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show, :destroy] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :postal_code, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :telephone_number, presence: true, format: {with: /\A\d{10,11}\z/}
  validates :is_active, inclusion: {in: [true, false]}


  def active_for_authentication?
    super && (is_active == false)
  end

  def name
    last_name + first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.order(created_at: :asc).page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    render :show
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_mypage_path
  end

#   # The path used after sign up for inactive accounts.
#   # def after_inactive_sign_up_path_for(resource)
#   #   super(resource)
#   # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mt-5 mx-auto">
      <h4 class="font-weight-bold"><%= @customer.last_name %><%= @customer.first_name %>さん会員情報編集</h4>
    </div>
  </div>
</div>

<div class="container mx-auto">
  <div class="offset-1">
    <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
    <form class="form-horizontal mt-5">
        <div class="form-row mt-5">
          <%= f.label "会員ID", class: "col-md-2 control-label" %>
          <div class="col">
            <%= @customer.id %>
          </div>
        </div>

        <div class="form-row mt-3">
          <%= f.label "氏名", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.text_field :last_name, class: "form-control"  %>
          </div>
          <div class="col">
            <%= f.text_field :first_name, class: "form-control"  %>
          </div>
        </div>

         <div class="form-row mt-3">
          <%= f.label "フリガナ", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.text_field :last_name_kana, class: "form-control"  %>
          </div>
          <div class="col">
            <%= f.text_field :first_name_kana, class: "form-control"  %>
          </div>
        </div>

         <div class="form-row mt-3">
          <%= f.label "郵便番号", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.text_field :postal_code, class: "form-control"  %>
          </div>
          <div class="col"></div>
        </div>

        <div class="form-row mt-3">
          <%= f.label "住所", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.text_field :address, class: "form-control"  %>
          </div>
        </div>

        <div class="form-row mt-3">
          <%= f.label "電話番号", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.text_field :telephone_number, class: "form-control"  %>
          </div>
          <div class="col"></div>
        </div>

        <div class="form-row mt-3">
          <%= f.label "メールアドレス", class: "col-md-2 control-label mt-2" %>
          <div class="col">
            <%= f.email_field :email, class: "form-control"  %>
          </div>
          <div class="col"></div>
        </div>

        <div class="form-row mt-3">
          <%= f.label "会員ステータス", class: "col-md-2 control-label mt-1" %>
          <div class="col">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "有効", value: :false, class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "退会", value: :true, class: "form-check-label" %>
            </div>
          <div class="col"></div>
        </div>

        <div class="col-md-10 m-4">
          <div class="offset-2">
            <%= f.submit '変更を保存', class: "btn btn-success" %>
          </div>
        </div>
    </form>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
    <div class="col-md-6 mt-5">
      <div class="offset-2">
        <h4 class="font-weight-bold">会員一覧</h4>
      </div>
    </div>
  </div>

<div class="table-responsive">
  <div class="col-md-10 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active == false %>
              <p class="text-success">有効</p>
            <% elsif customer.is_active == true %>
              <p class="text-danger">退会</p>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
    <div class="text-center"><%= paginate @customers %></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 mx-auto">
      <div class="offset-3">
        <h4 class="font-weight-bold"><%= @customer.name %>さんの会員詳細</h4>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mt-5 mb-5 mx-auto">
      <div class="offset-3">
        <table class="table table-borderless table-hover">
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>

          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>

          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>

          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>

          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>

          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_active == false %>
                <p class="text-success">有効</p>
              <% elsif @customer.is_active == true %>
                <p class="text-danger">退会</p>
              <% end %>
            </td>
          </tr>
        </table>
      </div>

      <div class="offset-5">
        <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success ml-2" %>
        <%= link_to '注文一覧を見る', admin_root_path(@customer), class: "btn btn-primary ml-5" %>
      </div>
    </div>
  </div>


</div>