config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'adminds/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/widthdraw' => 'customers#widthdraw', as: "customers_widthdraw"
    resources :customers, only:[:edit, :update]

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show, :destroy] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]

  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers" && path[:action] == "show"
      @orders = Order.where(customer_id: path[:id]).page(params[:page]).per(10).order("created_at DESC")
    else
      @orders = Order.page(params[:page]).per(10).order("created_at DESC")
    end
  end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mt-5">
      <div class="offset-1">
        <h4 class="font-weight-bold">注文履歴一覧</h4>
      </div>  
    </div>
  </div>
  
  <div class="row">
      <div class="table-responsive">
        <div class="col-md-10 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
          <table class="table table-hover">
            <thead class="thead-light">
              <tr>
                <th scope="col">購入日時</th>
                <th scope="col">購入者</th>
                <th scope="col">注文個数</th>
                <th scope="col">注文ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
              <tr>
                <td>
                <%= link_to admin_order_path(order.id) do %>
                  <%= order.created_at.strftime('%Y/%m/%d/ %H:%M:%S') %>
                <% end %>
                </td>
                <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
                <td><%= order.sum_order_products %></td>
                <td><%= order.status %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
  </div>
  

</div>