config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'adminds/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/widthdraw' => 'customers#widthdraw', as: "customers_widthdraw"
    resources :customers, only:[:edit, :update]

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show, :destroy] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_products, only: [:update]

  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def order_address
  	'〒' + postal_code  + "  " + address + "  " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :postal_code, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :telephone_number, presence: true, format: {with: /\A\d{10,11}\z/}
  validates :is_active, inclusion: {in: [true, false]}


  def active_for_authentication?
    super && (is_active == false)
  end

  def name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy
  attachment :image

  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false]}

  def self.search(search)
    if search
      Item.where(['content LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  belongs_to :customer

  def sum_order_products
    self.order_products.all.sum(:amount)
  end

  #注文の合計金額
  def total_price
    array = []
    self.order_products.each do |order_product|
      array << order_product.tax_included * order_product.amount
  end
    array.sum
  end

  enum payment_method: {"クレジットカード": 0, "銀行振込": 1 }
  enum status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備": 3, "発送済み": 4}

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {"製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to "/admin/genres"
  end

  def edit
    @genre =Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end


  protected
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers" && path[:action] == "show"
      @orders = Order.where(customer_id: path[:id]).page(params[:page]).per(10).order("created_at DESC")
    else
      @orders = Order.page(params[:page]).per(10).order("created_at DESC")
    end
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.order(created_at: :asc).page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  def search
    @items = Item.search(params[:search])
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image_id, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    customers_mypage_path
  end

  def after_sign_in_path_for(resource)
    if current_admin
      admin_root_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_active])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # 税込
  def tax_price(price)
    (price * 1.10).floor
  end

  # 小計
  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  # 合計
  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  def billing(order)
    total_price(current_customer.cart_items) + order.delivery_cost
  end

  def current_cart
    @cart_items = current_customer.cart_items
  end

end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class='navbar-brand p-3' href="/">
            <%= image_tag 'nagano_cake.png', size: '100x100' %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"  data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-right ml-auto">

              <ul class="nav navbar-nav">
              <% if customer_signed_in? %>
                <li class="customer-name mt-2">
                  ようこそ、<%= current_customer.last_name %>さん！
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "マイページ", customers_mypage_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
                </li>

              <% elsif admin_signed_in? %>
                <li class="nav-item ml-3">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-3">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-3">
                  <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary"%>
                </li>

                <li class="nav-item ml-3">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-3">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-3">
                  <form class="form-inline">
                    <%= form_with url: search_admin_items_path, local: true, method: :get do |f| %>
                      <%= f.text_field :search, class: "form-control mr-sm-2", style: "width:100px;", placeholder: "Search" %>
                      <%= f.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
                    <% end %>
                  </form>
                </li>

              <% else %>
                <li class="nav-item ml-5">
                  <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
                </li>

                <li class="nav-item ml-5">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>

    <footer></footer>

  </body>

</html>